version: '3'

services:
  mockServer:
    image: mockserver/mockserver:mockserver-snapshot
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/lolminer.json
    volumes:
      - type: bind
        source: ./config
        target: /config